/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Circle {
  'id' : string,
  'members' : Array<string>,
  'admin' : [] | [Principal],
  'name' : string,
  'description' : string,
  'isDemo' : boolean,
}
export type ExternalBlob = Uint8Array;
export interface MBTIType {
  'feeling' : bigint,
  'thinking' : bigint,
  'extrovert' : bigint,
  'introvert' : bigint,
}
export interface UserProfile {
  'bio' : string,
  'growthGoals' : Array<string>,
  'username' : string,
  'interests' : Array<string>,
  'userId' : string,
  'mbti' : [] | [MBTIType],
  'avatar' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMembersToCircle' : ActorMethod<[string, Array<string>], Circle>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCircle' : ActorMethod<[string, string, boolean], Circle>,
  'createOrUpdateProfile' : ActorMethod<[string, bigint, boolean], UserProfile>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfileById' : ActorMethod<[string], UserProfile>,
  'hasCircle' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isRegistered' : ActorMethod<[], boolean>,
  'manageChallenge' : ActorMethod<[string, string, string, boolean], string>,
  'removeChallenge' : ActorMethod<[string], undefined>,
  'removeCircle' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateChallenge' : ActorMethod<[string, string, string], undefined>,
  'updateCircle' : ActorMethod<[string, string, string], Circle>,
  'uploadBlob' : ActorMethod<[string, string, ExternalBlob], ExternalBlob>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];