/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Circle = IDL.Record({
  'id' : IDL.Text,
  'members' : IDL.Vec(IDL.Text),
  'admin' : IDL.Opt(IDL.Principal),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isDemo' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MBTIType = IDL.Record({
  'feeling' : IDL.Nat,
  'thinking' : IDL.Nat,
  'extrovert' : IDL.Nat,
  'introvert' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'growthGoals' : IDL.Vec(IDL.Text),
  'username' : IDL.Text,
  'interests' : IDL.Vec(IDL.Text),
  'userId' : IDL.Text,
  'mbti' : IDL.Opt(MBTIType),
  'avatar' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMembersToCircle' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [Circle], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCircle' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [Circle], []),
  'createOrUpdateProfile' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Bool],
      [UserProfile],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfileById' : IDL.Func([IDL.Text], [UserProfile], ['query']),
  'hasCircle' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'manageChallenge' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Text],
      [],
    ),
  'removeChallenge' : IDL.Func([IDL.Text], [], []),
  'removeCircle' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateChallenge' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateCircle' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Circle], []),
  'uploadBlob' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob],
      [ExternalBlob],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Circle = IDL.Record({
    'id' : IDL.Text,
    'members' : IDL.Vec(IDL.Text),
    'admin' : IDL.Opt(IDL.Principal),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isDemo' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MBTIType = IDL.Record({
    'feeling' : IDL.Nat,
    'thinking' : IDL.Nat,
    'extrovert' : IDL.Nat,
    'introvert' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'growthGoals' : IDL.Vec(IDL.Text),
    'username' : IDL.Text,
    'interests' : IDL.Vec(IDL.Text),
    'userId' : IDL.Text,
    'mbti' : IDL.Opt(MBTIType),
    'avatar' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMembersToCircle' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text)],
        [Circle],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCircle' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [Circle], []),
    'createOrUpdateProfile' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Bool],
        [UserProfile],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfileById' : IDL.Func([IDL.Text], [UserProfile], ['query']),
    'hasCircle' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'manageChallenge' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Text],
        [],
      ),
    'removeChallenge' : IDL.Func([IDL.Text], [], []),
    'removeCircle' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateChallenge' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateCircle' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Circle], []),
    'uploadBlob' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob],
        [ExternalBlob],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };